// quartz/components/FrontmatterAudit.tsx
// ------------------------------------------------------------------
// FRONTMATTER AUDIT COMPONENT
// Displays a completion dashboard showing what percentage of files
// have each frontmatter property set to true. Reads from the JSON
// report generated by scripts/frontmatter-audit.cjs
// ------------------------------------------------------------------

import vaultAudit from "../../quartz/static/data/frontmatter-audit.json"
import { QuartzComponent, QuartzComponentConstructor, QuartzComponentProps } from "./types"
import { useState, useEffect } from "preact/hooks"

// ---- Type definitions for the JSON report ----
interface AuditEntry { [key: string]: number }
interface PropertyInfo { label: string; description: string }
interface AuditData {
  generated: string
  properties: Record<string, PropertyInfo>
  vault: AuditEntry
  groups: Record<string, AuditEntry>
  entries: Record<string, AuditEntry>
}

const data = vaultAudit as AuditData

// ------------------------------------------------------------------
// COMPONENT
// ------------------------------------------------------------------

const FrontmatterAudit: QuartzComponent = ({ fileData }: QuartzComponentProps) => {
  // ---- State for active tooltip ----
  const [activeTooltip, setActiveTooltip] = useState<string | null>(null)

  // ---- Handle clicking outside to close tooltips ----
  useEffect(() => {
    if (!activeTooltip) return

    const handleOutsideClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement
      if (!target.closest(".info-button-wrapper")) {
        setActiveTooltip(null)
      }
    }

    document.addEventListener("click", handleOutsideClick)
    return () => document.removeEventListener("click", handleOutsideClick)
  }, [activeTooltip])

  // ---- Build the sorted list of properties ----
  const properties = Object.entries(data.vault || {})
    .map(([name, value]) => ({
      name,
      label: data.properties?.[name]?.label || name,
      description: data.properties?.[name]?.description || "",
      pct: Math.round(Number(value) || 0)
    }))
    .sort((a, b) => b.pct - a.pct)

  // ---- Calculate vault-wide average ----
  const vaultAvg = properties.length === 0
    ? 0
    : properties.reduce((sum, p) => sum + p.pct, 0) / properties.length
  const vaultPct = Math.round(vaultAvg)

  // ---- Color coding based on completion ----
  const getStatusColor = (pct: number) => {
    if (pct >= 90) return "var(--secondary)"
    if (pct >= 50) return "var(--tertiary)"
    return "var(--gray)"
  }

  // ---- Render ----
  return (
    <div class="audit-container">

      {/* ---- Component styles ---- */}
      <style>{`
        .audit-container {
          margin: 2rem 0;
          padding: 1.5rem;
          border: 1px solid var(--lightgray);
          border-radius: 8px;
          background-color: var(--light);
        }

        .audit-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2rem;
        }

        .audit-title-group h3 {
          margin: 0;
          font-size: 1.2rem;
        }

        .audit-meta {
          font-size: 0.75rem;
          color: var(--gray);
          font-family: var(--codeFont);
        }

        .audit-badge {
          padding: 0.4rem 0.8rem;
          border-radius: 6px;
          background: var(--highlight);
          color: var(--secondary);
          font-weight: 700;
          font-family: var(--codeFont);
        }

        .audit-grid {
          display: grid;
          gap: 1.2rem;
        }

        .audit-item {
          display: flex;
          flex-direction: column;
          gap: 0.4rem;
        }

        .audit-label-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-size: 0.85rem;
          font-family: var(--codeFont);
        }

        .audit-name-group {
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }

        .audit-name {
          color: var(--dark);
          font-weight: 500;
        }

        .audit-value {
          color: var(--gray);
        }

        /* ---- Info button and tooltip ---- */
        .info-button-wrapper {
          position: relative;
          display: inline-flex;
          align-items: center;
        }

        .info-button {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          width: 18px;
          height: 18px;
          border-radius: 50%;
          border: 1px solid var(--gray);
          background: transparent;
          color: var(--gray);
          font-size: 0.7rem;
          font-weight: bold;
          cursor: pointer;
          padding: 0;
          line-height: 1;
          font-family: var(--bodyFont);
          transition: all 0.15s ease;
        }

        .info-button:hover,
        .info-button.active {
          background: var(--dark);
          color: white;
          border-color: var(--dark);
        }

        .info-tooltip {
          position: absolute;
          top: calc(100% + 8px); 
          left: 50%;
          transform: translateX(-50%);
          background: var(--dark);
          color: white;
          padding: 0.6rem 0.85rem;
          border-radius: 6px;
          font-size: 0.8rem;
          width: 260px;
          line-height: 1.4;
          z-index: 999;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
          font-family: var(--bodyFont);
        }

        /* Tooltip arrow pointer */
        .info-tooltip::before {
          content: "";
          position: absolute;
          bottom: 100%;
          left: 50%;
          transform: translateX(-50%);
          border-width: 5px;
          border-style: solid;
          border-color: transparent transparent var(--dark) transparent;
        }

        /* ---- Progress bar ---- */
        .progress-track {
          height: 6px;
          width: 100%;
          background: var(--lightgray);
          border-radius: 10px;
          overflow: hidden;
        }

        .progress-fill {
          height: 100%;
          border-radius: 10px;
          transition: width 0.6s cubic-bezier(0.22, 1, 0.36, 1);
        }
      `}</style>

      {/* ---- Header with title and overall percentage ---- */}
      <div class="audit-header">
        <div class="audit-title-group">
          <h3>Frontmatter Audit</h3>
          <span class="audit-meta">Analyzed on {data.generated}</span>
        </div>
        <div class="audit-badge">{vaultPct}% Complete</div>
      </div>

      {/* ---- Property list with progress bars ---- */}
      <div class="audit-grid">
        {properties.map(({ name, label, description, pct }) => (
          <div class="audit-item" key={name}>

            {/* ---- Label row: name, info button, percentage ---- */}
            <div class="audit-label-row">
              <div class="audit-name-group">
                <span class="audit-name">{label}</span>

                {/* Info button (only if description exists) */}
                {description && (
                  <div
                    class="info-button-wrapper"
                    style={{ zIndex: activeTooltip === name ? "1000" : "1" }}
                  >
                    <button
                      class={`info-button ${activeTooltip === name ? 'active' : ''}`}
                      onClick={(e) => {
                        e.stopPropagation()
                        setActiveTooltip(activeTooltip === name ? null : name)
                      }}
                      aria-label={`Info about ${label}`}
                    >
                      i
                    </button>
                    {activeTooltip === name && (
                      <div class="info-tooltip">
                        {description}
                      </div>
                    )}
                  </div>
                )}
              </div>
              <span class="audit-value">{pct}%</span>
            </div>

            {/* ---- Progress bar ---- */}
            <div class="progress-track">
              <div
                class="progress-fill"
                style={{
                  width: `${pct}%`,
                  backgroundColor: getStatusColor(pct)
                }}
              />
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// ------------------------------------------------------------------
// EXPORT
// ------------------------------------------------------------------

export default (() => FrontmatterAudit) satisfies QuartzComponentConstructor